### ISSUE TITLE
References: bad URLs

### ISSUE THREAD

**Issue by sginoza** [rfc-editor/draft-irtf-cfrg-hash-to-curve#43]
References:  The provided URLs for [jubjub-fq] and [W19]*
each yield a 404 error.  Please provide working URLs.

Original:
 [jubjub-fq]
            "zkcrypto/jubjub - fq.rs", 2019,
            <https://github.com/zkcrypto/jubjub/blob/master/src/
            fq.rs>.

 [W19]      Wahby, R.S., "An explicit, generic parameterization for                               
            the Shallue--van de Woestijne map", 2019,
            <https://github.com/cfrg/draft-irtf-cfrg-hash-to-
            curve/raw/master/doc/svdw_params.pdf>.

**Comment by armfazh** [comment]
Updated links:

```
jubjub-fq:
  target: https://github.com/zkcrypto/jubjub/pull/18

W19:
  target: https://github.com/cfrg/draft-irtf-cfrg-hash-to-curve/blob/draft-irtf-cfrg-hash-to-curve-14/doc/svdw_params.pdf
```
