### ISSUE TITLE
References: redirects 

### ISSUE THREAD

**Issue by sginoza** [rfc-editor/draft-irtf-cfrg-hash-to-curve#44]
References:  The following provided "CRC Press" URLs
steer to routledge.com pages.  Should these be updated?

Original:
 [CFADLNV05]
            Cohen, H., Frey, G., Avanzi, R., Doche, C., Lange, T.,
            Nguyen, K., and F. Vercauteren, "Handbook of Elliptic and                             
            Hyperelliptic Curve Cryptography", ISBN 9781584885184,
            publisher Chapman and Hall / CRC, 2005,
            <https://www.crcpress.com/9781584885184>.
...
 [W08]      Washington, L.C., "Elliptic curves: Number theory and                                 
            cryptography", ISBN 9781420071467, publisher Chapman and
            Hall / CRC, edition 2nd, 2008,
            <https://www.crcpress.com/9781420071467>.

**Comment by armfazh** [comment]
these are links to the webpage of the book hosted by the authors.

```
CFADLNV05:
   target: https://www.hyperelliptic.org/HEHCC/

W08:
   target: http://www.math.umd.edu/~lcw/ellipticcurves.html


```
